/**
 * Centralized constants for the Shaaka backend
 * All magic numbers and strings should be defined here
 */

// Order status constants
const ORDER_STATUS = {
  PLACED: 'PLACED',
  PAYMENT_PENDING: 'PAYMENT_PENDING',
  PAYMENT_FAILED: 'PAYMENT_FAILED',
  CONFIRMED: 'CONFIRMED',
  PACKED: 'PACKED',
  READY_TO_DELIVER: 'READY_TO_DELIVER',
  HANDED_TO_AGENT: 'HANDED_TO_AGENT',
  DELIVERED: 'DELIVERED',
  CANCELLED: 'CANCELLED',
  REFUND_INITIATED: 'REFUND_INITIATED',
  REFUNDED: 'REFUNDED',
};

// Payment status constants
const PAYMENT_STATUS = {
  PENDING: 'PENDING',
  AUTHORIZED: 'AUTHORIZED',
  PAID: 'PAID',
  FAILED: 'FAILED',
  REFUND_INITIATED: 'REFUND_INITIATED',
  PARTIALLY_REFUNDED: 'PARTIALLY_REFUNDED',
  REFUNDED: 'REFUNDED',
};

// Payment method constants
const PAYMENT_METHOD = {
  RAZORPAY: 'RAZORPAY',
  COD: 'COD',
};

// Vendor status constants
const VENDOR_STATUS = {
  PENDING_APPROVAL: 'PENDING_APPROVAL',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED',
  SUSPENDED: 'SUSPENDED',
};

// Vendor item status (for mixed orders)
const VENDOR_ITEM_STATUS = {
  PENDING: 'PENDING',
  CONFIRMED: 'CONFIRMED',
  PACKED: 'PACKED',
  OUT_FOR_DELIVERY: 'OUT_FOR_DELIVERY',
  DELIVERED: 'DELIVERED',
  CANCELLED: 'CANCELLED',
};

// Staff allowed order status transitions (admin products only)
const STAFF_ALLOWED_STATUS = [
  ORDER_STATUS.PACKED,
  ORDER_STATUS.READY_TO_DELIVER,
  ORDER_STATUS.HANDED_TO_AGENT,
];

// Valid order status transitions
const ORDER_STATUS_TRANSITIONS = {
  [ORDER_STATUS.PLACED]: [ORDER_STATUS.PAYMENT_PENDING, ORDER_STATUS.CONFIRMED, ORDER_STATUS.CANCELLED],
  [ORDER_STATUS.PAYMENT_PENDING]: [ORDER_STATUS.CONFIRMED, ORDER_STATUS.PAYMENT_FAILED, ORDER_STATUS.CANCELLED],
  [ORDER_STATUS.PAYMENT_FAILED]: [ORDER_STATUS.PAYMENT_PENDING, ORDER_STATUS.CANCELLED],
  [ORDER_STATUS.CONFIRMED]: [ORDER_STATUS.PACKED, ORDER_STATUS.CANCELLED],
  [ORDER_STATUS.PACKED]: [ORDER_STATUS.READY_TO_DELIVER, ORDER_STATUS.CANCELLED],
  [ORDER_STATUS.READY_TO_DELIVER]: [ORDER_STATUS.HANDED_TO_AGENT],
  [ORDER_STATUS.HANDED_TO_AGENT]: [ORDER_STATUS.DELIVERED],
  [ORDER_STATUS.DELIVERED]: [],
  [ORDER_STATUS.CANCELLED]: [ORDER_STATUS.REFUND_INITIATED],
  [ORDER_STATUS.REFUND_INITIATED]: [ORDER_STATUS.REFUNDED],
  [ORDER_STATUS.REFUNDED]: [],
};

// Pagination defaults
const PAGINATION = {
  DEFAULT_PAGE: 1,
  DEFAULT_LIMIT: 12,
  MAX_LIMIT: 100,
  SEARCH_LIMIT: 50,
};

// Cart limits
const CART_LIMITS = {
  MAX_QUANTITY_PER_ITEM: 10,
  MAX_ITEMS: 50,
};

// Review limits
const REVIEW_LIMITS = {
  MIN_RATING: 1,
  MAX_RATING: 5,
  MAX_COMMENT_LENGTH: 1000,
  MAX_IMAGES: 5,
};

// Cache TTL (in seconds)
const CACHE_TTL = {
  CATEGORIES: 3600,        // 1 hour
  PRODUCTS_LIST: 300,      // 5 minutes  
  PRODUCT_DETAIL: 600,     // 10 minutes
  FEATURED_PRODUCTS: 1800, // 30 minutes
  DISTANCE: 86400,         // 24 hours
  USER_PROFILE: 300,       // 5 minutes
};

// Rate limit settings
const RATE_LIMITS = {
  OTP: {
    WINDOW_MS: 15 * 60 * 1000, // 15 minutes
    MAX_REQUESTS: 5,
  },
  ORDER: {
    WINDOW_MS: 60 * 1000, // 1 minute
    MAX_REQUESTS: 5,
  },
  API: {
    WINDOW_MS: 60 * 1000, // 1 minute
    MAX_REQUESTS: 100,
  },
};

// Payment window
const PAYMENT_WINDOW_MINUTES = 30;

// Delivery settings
const DELIVERY = {
  MIN_ORDER_VALUE: 200,
  FREE_DELIVERY_THRESHOLD: 500,
  DELIVERY_CHARGE: 40,
  MAX_DELIVERY_RADIUS_KM: 25,
};

// Product source
const PRODUCT_SOURCE = {
  ADMIN: 'ADMIN',
  VENDOR: 'VENDOR',
};

// Sort options
const SORT_OPTIONS = {
  'price-asc': { minPrice: 1 },
  'price-desc': { minPrice: -1 },
  'rating': { averageRating: -1 },
  'newest': { createdAt: -1 },
  'popular': { totalSales: -1 },
};

// Address labels
const ADDRESS_LABELS = ['Home', 'Office', 'Other'];

// Audit log actions
const AUDIT_ACTIONS = {
  USER_LOGIN: 'USER_LOGIN',
  USER_LOGOUT: 'USER_LOGOUT',
  ORDER_CREATED: 'ORDER_CREATED',
  ORDER_STATUS_UPDATED: 'ORDER_STATUS_UPDATED',
  ORDER_CANCELLED: 'ORDER_CANCELLED',
  PAYMENT_COMPLETED: 'PAYMENT_COMPLETED',
  PAYMENT_FAILED: 'PAYMENT_FAILED',
  REFUND_INITIATED: 'REFUND_INITIATED',
  PRODUCT_CREATED: 'PRODUCT_CREATED',
  PRODUCT_UPDATED: 'PRODUCT_UPDATED',
  PRODUCT_DELETED: 'PRODUCT_DELETED',
  VENDOR_REGISTERED: 'VENDOR_REGISTERED',
  VENDOR_APPROVED: 'VENDOR_APPROVED',
  VENDOR_REJECTED: 'VENDOR_REJECTED',
  VENDOR_SUSPENDED: 'VENDOR_SUSPENDED',
};

module.exports = {
  ORDER_STATUS,
  PAYMENT_STATUS,
  PAYMENT_METHOD,
  VENDOR_STATUS,
  VENDOR_ITEM_STATUS,
  STAFF_ALLOWED_STATUS,
  ORDER_STATUS_TRANSITIONS,
  PAGINATION,
  CART_LIMITS,
  REVIEW_LIMITS,
  CACHE_TTL,
  RATE_LIMITS,
  PAYMENT_WINDOW_MINUTES,
  DELIVERY,
  PRODUCT_SOURCE,
  SORT_OPTIONS,
  ADDRESS_LABELS,
  AUDIT_ACTIONS,
};
